apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-configmap
data:
  search.service.id: search-service
  search.service.url: http://search-service:8090
  search.service.path: Path= /search/*