apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-depl
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: sangameshwar18/discovery-server:1.0.0
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
spec:
  selector:
    app: discovery-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 30000


