apiVersion: apps/v1
kind: Deployment
metadata:
  name: fare-service
  labels:
    app: fare-service
spec:
  replicas: 1
  selector:
    app: fare-service
  template:
    metadata:
      labels:
        app: fare-service
    spec:
      containers:
        - name: fare-service
          image: sangameshwar18/fare-service:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-configmap
                  key: database-url
            
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-username
            
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            
            - name: eureka.client.service-url.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-configmap
                  key: eureka-server-url
  
--- 

apiVersion: v1
kind: Service
metadata:
  name: fare-service
spec:
  selector:
    app: fare-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP