apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: sangameshwar18/flight-search-microservice:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-configmap
                  key: database-url
            
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-username
            
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            
            - name: eureka.client.service-url.defaultzone
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-configmap
                  key: eureka-server-url
            
            - name: eureka.instance.prefer-ip-address
              value: true
            
            - name: eureka.client.fetch-registry
              value: true
            
            - name: eureka.client.register-with-eureka
              value: true
            


---

apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: serach-service
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP



