apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sangameshwar18/user-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
          env:
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-url
                  key: database-url
            
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-username
            
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            
            - name: eureka.client.service-url.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-configmap
                  key: eureka-server-url

--- 

apiVersion: v1
kindService: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP